In [25]:
import pandas as pd

# Probeer met puntkomma als scheidingsteken
df = pd.read_csv("Metric Store - Service Swaps.csv", encoding="latin1", sep=";")

print(df.head())
print(df.info())

  Geographical Indicator Colour Category '23-01 '23-02 '23-03 '23-04 '23-05  \
0  50/50 Leger des Heils        Deluxe 7    NaN    NaN    NaN    NaN    NaN
1                    NaN      Original 1    NaN    NaN    NaN    NaN    NaN
2                    NaN     Original 1+    NaN    NaN    NaN    NaN    NaN
3                    NaN         Power 1    NaN    NaN    NaN    NaN    NaN
4                    NaN         Power 7    NaN    NaN    NaN    NaN    NaN

  '23-06 '23-07 '23-08  ... '24-12 '25-01 '25-02 '25-03 '25-04 '25-05 '25-06  \
0    NaN    NaN    NaN  ...    NaN    NaN    NaN    NaN    NaN    NaN    NaN
1    NaN    NaN    NaN  ...    NaN    NaN    NaN    NaN    NaN    NaN    NaN
2    NaN    NaN    NaN  ...    NaN    NaN    NaN    NaN    NaN    NaN    NaN
3    NaN    NaN    NaN  ...    NaN    NaN    NaN    NaN    NaN    NaN    NaN
4    NaN    NaN    NaN  ...    NaN    NaN    NaN    NaN    NaN    NaN    NaN

  '25-07 '25-08 '25-09
0    NaN    NaN    NaN
1    NaN    NaN    NaN
2    NaN    NaN    NaN
3    NaN    NaN    NaN
4    NaN    NaN    NaN

[5 rows x 35 columns]
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 526 entries, 0 to 525
Data columns (total 35 columns):
 #   Column                  Non-Null Count  Dtype
---  ------                  --------------  -----
 0   Geographical Indicator  76 non-null     object
 1   Colour Category         526 non-null    object
 2   '23-01                  268 non-null    object
 3   '23-02                  265 non-null    object
 4   '23-03                  257 non-null    object
 5   '23-04                  237 non-null    object
 6   '23-05                  236 non-null    object
 7   '23-06                  235 non-null    object
 8   '23-07                  234 non-null    object
 9   '23-08                  237 non-null    object
 10  '23-09                  236 non-null    object
 11  '23-10                  237 non-null    object
 12  '23-11                  235 non-null    object
 13  '23-12                  233 non-null    object
 14  '24-01                  231 non-null    object
 15  '24-02                  230 non-null    object
 16  '24-03                  234 non-null    object
 17  '24-04                  225 non-null    object
 18  '24-05                  229 non-null    object
 19  '24-06                  229 non-null    object
 20  '24-07                  228 non-null    object
 21  '24-08                  226 non-null    object
 22  '24-09                  230 non-null    object
 23  '24-10                  227 non-null    object
 24  '24-11                  227 non-null    object
 25  '24-12                  227 non-null    object
 26  '25-01                  227 non-null    object
 27  '25-02                  226 non-null    object
 28  '25-03                  227 non-null    object
 29  '25-04                  227 non-null    object
 30  '25-05                  228 non-null    object
 31  '25-06                  227 non-null    object
 32  '25-07                  227 non-null    object
 33  '25-08                  225 non-null    object
 34  '25-09                  214 non-null    object
dtypes: object(35)
memory usage: 144.0+ KB
None

In [26]:
df.head(50)

,Geographical Indicator,Colour Category,'23-01,'23-02,'23-03,'23-04,'23-05,'23-06,'23-07,'23-08,...,'24-12,'25-01,'25-02,'25-03,'25-04,'25-05,'25-06,'25-07,'25-08,'25-09
0,50/50 Leger des Heils,Deluxe 7,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,NaN,Original 1,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,NaN,Original 1+,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,NaN,Power 1,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,NaN,Power 7,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
5,NaN,Power Plus,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
6,NaN,Totaal,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
7,Aachen,Deluxe 7,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
8,NaN,Original 1,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
9,NaN,Original 1+,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
10,NaN,Power 1,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
11,NaN,Power 7,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
12,NaN,Power Plus,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
13,NaN,Totaal,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
14,Aalborg,Deluxe 7,"35,00","28,00","46,00","40,00","34,00","25,00","9,00","30,00",...,"32,00","30,00","43,00","27,00","43,00","40,00","28,00","24,00","33,00","9,00"
15,NaN,Original 1,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
16,NaN,Original 1+,"1,00","3,00",NaN,"3,00","1,00",NaN,"1,00","5,00",...,"3,00",NaN,"2,00","5,00","1,00","3,00","2,00","5,00","1,00",NaN
17,NaN,Power 1,"14,00","5,00","11,00","12,00","7,00","3,00","4,00","9,00",...,"21,00","25,00","21,00","22,00","22,00","26,00","25,00","26,00","19,00","4,00"
18,NaN,Power 7,"69,00","51,00","55,00","44,00","53,00","32,00","42,00","33,00",...,"82,00","142,00","118,00","98,00","93,00","79,00","60,00","38,00","42,00","4,00"
19,NaN,Power Plus,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
20,NaN,Totaal,"119,00","87,00","112,00","99,00","95,00","60,00","56,00","77,00",...,"138,00","197,00","184,00","152,00","159,00","148,00","115,00","93,00","95,00","17,00"
21,Aarhus,Deluxe 7,"86,00","119,00","173,00","88,00","123,00","91,00","77,00","86,00",...,"73,00","91,00","92,00","100,00","94,00","106,00","71,00","63,00","107,00","12,00"
22,NaN,Original 1,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
23,NaN,Original 1+,NaN,NaN,"1,00",NaN,"2,00",NaN,NaN,NaN,...,NaN,"1,00",NaN,NaN,"1,00",NaN,NaN,NaN,NaN,NaN
24,NaN,Power 1,"4,00","13,00","10,00","11,00","7,00","6,00","11,00","11,00",...,"39,00","38,00","34,00","43,00","52,00","37,00","39,00","38,00","46,00","3,00"
25,NaN,Power 7,"30,00","27,00","52,00","50,00","31,00","30,00","27,00","36,00",...,"36,00","46,00","75,00","83,00","68,00","74,00","67,00","58,00","65,00","12,00"
26,NaN,Power Plus,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
27,NaN,Totaal,"120,00","159,00","236,00","149,00","163,00","127,00","115,00","133,00",...,"148,00","176,00","201,00","226,00","215,00","217,00","177,00","159,00","218,00","27,00"
28,Amsterdam,Deluxe 7,"1.909,00","2.017,00","2.078,00","1.999,00","2.237,00","2.323,00","2.105,00","2.150,00",...,"1.905,00","2.474,00","2.142,00","2.422,00","2.615,00","2.355,00","2.272,00","2.481,00","2.150,00","457,00"
29,NaN,Original 1,"3.549,00","3.533,00","3.475,00","3.163,00","3.358,00","3.419,00","2.993,00","3.114,00",...,"2.889,00","3.516,00","2.912,00","2.943,00","2.999,00","2.835,00","2.699,00","2.785,00","2.737,00","553,00"
30,NaN,Original 1+,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
31,NaN,Power 1,"593,00","530,00","600,00","555,00","570,00","497,00","567,00","621,00",...,"1.731,00","2.031,00","1.549,00","1.609,00","1.384,00","1.281,00","1.455,00","1.615,00","1.401,00","243,00"
32,NaN,Power 7,"805,00","784,00","912,00","813,00","895,00","896,00","813,00","808,00",...,"885,00","1.099,00","874,00","1.079,00","1.048,00","989,00","1.032,00","1.237,00","1.014,00","160,00"
33,NaN,Power Plus,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
34,NaN,Totaal,"6.856,00","6.864,00","7.065,00","6.530,00","7.060,00","7.135,00","6.478,00","6.693,00",...,"7.410,00","9.120,00","7.477,00","8.053,00","8.046,00","7.460,00","7.458,00","8.118,00","7.302,00","1.413,00"
35,Antwerp,Deluxe 7,"352,00","353,00","365,00","351,00","333,00","296,00","307,00","364,00",...,"322,00","338,00","288,00","351,00","398,00","345,00","299,00","356,00","317,00","70,00"
36,NaN,Original 1,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
37,NaN,Original 1+,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
38,NaN,Power 1,"141,00","111,00","125,00","132,00","150,00","96,00","118,00","124,00",...,"155,00","154,00","152,00","160,00","147,00","114,00","125,00","103,00","105,00","21,00"
39,NaN,Power 7,"312,00","322,00","277,00","266,00","264,00","224,00","198,00","270,00",...,"147,00","166,00","131,00","183,00","155,00","163,00","175,00","183,00","171,00","37,00"
40,NaN,Power Plus,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,"91,00","145,00","111,00","80,00","92,00","92,00","81,00","97,00","70,00","8,00"
41,NaN,Totaal,"805,00","786,00","767,00","749,00","747,00","616,00","623,00","758,00",...,"715,00","803,00","682,00","774,00","792,00","714,00","680,00","739,00","663,00","136,00"
42,Arnhem,Deluxe 7,"49,00","39,00","52,00","46,00","59,00","47,00","52,00","61,00",...,"57,00","66,00","69,00","51,00","66,00","66,00","57,00","60,00","48,00","10,00"
43,NaN,Original 1,"41,00","33,00","38,00","26,00","46,00","25,00","31,00","37,00",...,"32,00","50,00","40,00","47,00","38,00","31,00","37,00","34,00","34,00","8,00"
44,NaN,Original 1+,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
45,NaN,Power 1,"20,00","11,00","15,00","11,00","13,00","10,00","27,00","16,00",...,"60,00","72,00","61,00","61,00","68,00","62,00","55,00","56,00","78,00","7,00"
46,NaN,Power 7,"64,00","49,00","45,00","57,00","56,00","66,00","78,00","65,00",...,"104,00","97,00","79,00","74,00","78,00","111,00","80,00","96,00","78,00","17,00"
47,NaN,Power Plus,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
48,NaN,Totaal,"174,00","132,00","150,00","140,00","174,00","148,00","188,00","179,00",...,"253,00","285,00","249,00","233,00","250,00","270,00","229,00","246,00","238,00","42,00"
49,Barcelona,Deluxe 7,"104,00","80,00","75,00","78,00","90,00","98,00","86,00","90,00",...,"78,00","134,00","112,00","134,00","140,00","155,00","133,00","195,00","176,00","29,00"

In [27]:
# verwijder eventuele spaties
df["Geographical Indicator"] = df["Geographical Indicator"].astype(str).str.strip()

# check unieke waarden
print(df["Geographical Indicator"].unique())

['50/50 Leger des Heils' 'nan' 'Aachen' 'Aalborg' 'Aarhus' 'Amsterdam'
 'Antwerp' 'Arnhem' 'Barcelona' 'Barneveld (distributie)' 'Berlin'
 'Bike Repair Shop Sittard' 'Bonn' 'Braunschweig' 'Breda' 'Bremen'
 'Brussel' 'Cologne' 'Copenhagen' 'Delft' 'Den Bosch' 'Den Haag' 'Dresden'
 'Düsseldorf' 'Ede - Wageningen' 'Eindhoven' 'Enschede' 'Frankfurt'
 'Freiburg' 'Gent' 'Göttingen' 'Groningen' 'Haarlem' 'Halle' 'Hamburg'
 'Hannover' 'Heidelberg' 'Karlsruhe' 'Kiel' 'Leeuwarden' 'Leiden'
 'Leipzig' 'Leuven' 'London' 'Lübeck' 'Lyon' 'Maastricht'
 'Mainz-Wiesbaden' 'Mechelen' 'Milan' 'Munich' 'Münster' 'Nantes'
 'Nijmegen' 'Odense' 'Oldenburg' 'Osnabrück' 'Paris' 'PI' 'Potsdam'
 'Regional Warehouse Belgium' 'Regional Warehouse Den Bosch - Eindhoven'
 'Regional Warehouse Den Hoorn' 'Regional Warehouse Groningen'
 'Regional Warehouse Tilburg - Breda' 'Regional Warehouse Wijchen'
 'Rotterdam' 'Smart Velo Mobility' 'Strasbourg' 'Stuttgart' 'Tilburg'
 'Toulouse' 'Utrecht' 'Vienna' 'Wolfsburg' 'Zwolle' 'Eindtotaal']

In [28]:
# start en eind index vinden
start_idx = df.index[df["Geographical Indicator"] == "Amsterdam"][0]
end_idx   = df.index[df["Geographical Indicator"] == "Antwerp"][0]

# subset pakken (inclusief Amsterdam, tot Antwerpen-1)
subset = df.loc[start_idx:end_idx-1].copy()

# NaN's aanvullen met laatst bekende locatie
subset["Geographical Indicator"] = subset["Geographical Indicator"].replace("nan", pd.NA).ffill()

print(subset.head(15))

   Geographical Indicator Colour Category    '23-01    '23-02    '23-03  \
28              Amsterdam        Deluxe 7  1.909,00  2.017,00  2.078,00
29              Amsterdam      Original 1  3.549,00  3.533,00  3.475,00
30              Amsterdam     Original 1+       NaN       NaN       NaN
31              Amsterdam         Power 1    593,00    530,00    600,00
32              Amsterdam         Power 7    805,00    784,00    912,00
33              Amsterdam      Power Plus       NaN       NaN       NaN
34              Amsterdam          Totaal  6.856,00  6.864,00  7.065,00

      '23-04    '23-05    '23-06    '23-07    '23-08  ...    '24-12    '25-01  \
28  1.999,00  2.237,00  2.323,00  2.105,00  2.150,00  ...  1.905,00  2.474,00
29  3.163,00  3.358,00  3.419,00  2.993,00  3.114,00  ...  2.889,00  3.516,00
30       NaN       NaN       NaN       NaN       NaN  ...       NaN       NaN
31    555,00    570,00    497,00    567,00    621,00  ...  1.731,00  2.031,00
32    813,00    895,00    896,00    813,00    808,00  ...    885,00  1.099,00
33       NaN       NaN       NaN       NaN       NaN  ...       NaN       NaN
34  6.530,00  7.060,00  7.135,00  6.478,00  6.693,00  ...  7.410,00  9.120,00

      '25-02    '25-03    '25-04    '25-05    '25-06    '25-07    '25-08  \
28  2.142,00  2.422,00  2.615,00  2.355,00  2.272,00  2.481,00  2.150,00
29  2.912,00  2.943,00  2.999,00  2.835,00  2.699,00  2.785,00  2.737,00
30       NaN       NaN       NaN       NaN       NaN       NaN       NaN
31  1.549,00  1.609,00  1.384,00  1.281,00  1.455,00  1.615,00  1.401,00
32    874,00  1.079,00  1.048,00    989,00  1.032,00  1.237,00  1.014,00
33       NaN       NaN       NaN       NaN       NaN       NaN       NaN
34  7.477,00  8.053,00  8.046,00  7.460,00  7.458,00  8.118,00  7.302,00

      '25-09
28    457,00
29    553,00
30       NaN
31    243,00
32    160,00
33       NaN
34  1.413,00

[7 rows x 35 columns]

In [29]:
subset

,Geographical Indicator,Colour Category,'23-01,'23-02,'23-03,'23-04,'23-05,'23-06,'23-07,'23-08,...,'24-12,'25-01,'25-02,'25-03,'25-04,'25-05,'25-06,'25-07,'25-08,'25-09
28,Amsterdam,Deluxe 7,"1.909,00","2.017,00","2.078,00","1.999,00","2.237,00","2.323,00","2.105,00","2.150,00",...,"1.905,00","2.474,00","2.142,00","2.422,00","2.615,00","2.355,00","2.272,00","2.481,00","2.150,00","457,00"
29,Amsterdam,Original 1,"3.549,00","3.533,00","3.475,00","3.163,00","3.358,00","3.419,00","2.993,00","3.114,00",...,"2.889,00","3.516,00","2.912,00","2.943,00","2.999,00","2.835,00","2.699,00","2.785,00","2.737,00","553,00"
30,Amsterdam,Original 1+,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
31,Amsterdam,Power 1,"593,00","530,00","600,00","555,00","570,00","497,00","567,00","621,00",...,"1.731,00","2.031,00","1.549,00","1.609,00","1.384,00","1.281,00","1.455,00","1.615,00","1.401,00","243,00"
32,Amsterdam,Power 7,"805,00","784,00","912,00","813,00","895,00","896,00","813,00","808,00",...,"885,00","1.099,00","874,00","1.079,00","1.048,00","989,00","1.032,00","1.237,00","1.014,00","160,00"
33,Amsterdam,Power Plus,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
34,Amsterdam,Totaal,"6.856,00","6.864,00","7.065,00","6.530,00","7.060,00","7.135,00","6.478,00","6.693,00",...,"7.410,00","9.120,00","7.477,00","8.053,00","8.046,00","7.460,00","7.458,00","8.118,00","7.302,00","1.413,00"

In [30]:
import pandas as pd

# Probeer met puntkomma als scheidingsteken
df = pd.read_csv("combined_metrics (1).csv")

print(df.head())
print(df.info())

  Geographical Indicator Colour Category  '23-01  '23-02  '23-03  '23-04  \
0  50/50 Leger des Heils        Deluxe 7     NaN     NaN     NaN     NaN
1                    NaN      Original 1     NaN     NaN     NaN     NaN
2                    NaN     Original 1+     NaN     NaN     NaN     NaN
3                    NaN         Power 1     NaN     NaN     NaN     NaN
4                    NaN         Power 7     NaN     NaN     NaN     NaN

   '23-05  '23-06  '23-07  '23-08  ...  '24-12  '25-01  '25-02  '25-03  \
0     NaN     NaN     NaN     NaN  ...     NaN     NaN     NaN     NaN
1     NaN     NaN     NaN     NaN  ...     NaN     NaN     NaN     NaN
2     NaN     NaN     NaN     NaN  ...     NaN     NaN     NaN     NaN
3     NaN     NaN     NaN     NaN  ...     NaN     NaN     NaN     NaN
4     NaN     NaN     NaN     NaN  ...     NaN     NaN     NaN     NaN

   '25-04  '25-05  '25-06  '25-07  '25-08  '25-09
0     NaN     NaN     NaN     NaN     NaN     NaN
1     NaN     NaN     NaN     NaN     NaN     NaN
2     NaN     NaN     NaN     NaN     NaN     NaN
3     NaN     NaN     NaN     NaN     NaN     NaN
4     NaN     NaN     NaN     NaN     NaN     NaN

[5 rows x 35 columns]
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1578 entries, 0 to 1577
Data columns (total 35 columns):
 #   Column                  Non-Null Count  Dtype
---  ------                  --------------  -----
 0   Geographical Indicator  228 non-null    object
 1   Colour Category         1578 non-null   object
 2   '23-01                  832 non-null    float64
 3   '23-02                  817 non-null    float64
 4   '23-03                  783 non-null    float64
 5   '23-04                  762 non-null    float64
 6   '23-05                  747 non-null    float64
 7   '23-06                  743 non-null    float64
 8   '23-07                  734 non-null    float64
 9   '23-08                  742 non-null    float64
 10  '23-09                  738 non-null    float64
 11  '23-10                  739 non-null    float64
 12  '23-11                  728 non-null    float64
 13  '23-12                  719 non-null    float64
 14  '24-01                  717 non-null    float64
 15  '24-02                  719 non-null    float64
 16  '24-03                  725 non-null    float64
 17  '24-04                  716 non-null    float64
 18  '24-05                  716 non-null    float64
 19  '24-06                  719 non-null    float64
 20  '24-07                  714 non-null    float64
 21  '24-08                  709 non-null    float64
 22  '24-09                  710 non-null    float64
 23  '24-10                  701 non-null    float64
 24  '24-11                  700 non-null    float64
 25  '24-12                  698 non-null    float64
 26  '25-01                  694 non-null    float64
 27  '25-02                  685 non-null    float64
 28  '25-03                  694 non-null    float64
 29  '25-04                  691 non-null    float64
 30  '25-05                  693 non-null    float64
 31  '25-06                  693 non-null    float64
 32  '25-07                  689 non-null    float64
 33  '25-08                  688 non-null    float64
 34  '25-09                  209 non-null    float64
dtypes: float64(33), object(2)
memory usage: 431.6+ KB
None

In [31]:
df.head(50)

,Geographical Indicator,Colour Category,'23-01,'23-02,'23-03,'23-04,'23-05,'23-06,'23-07,'23-08,...,'24-12,'25-01,'25-02,'25-03,'25-04,'25-05,'25-06,'25-07,'25-08,'25-09
0,50/50 Leger des Heils,Deluxe 7,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,NaN,Original 1,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,NaN,Original 1+,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,NaN,Power 1,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,NaN,Power 7,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
5,NaN,Power Plus,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
6,NaN,Totaal,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
7,Aachen,Deluxe 7,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
8,NaN,Original 1,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
9,NaN,Original 1+,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
10,NaN,Power 1,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
11,NaN,Power 7,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
12,NaN,Power Plus,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
13,NaN,Totaal,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
14,Aalborg,Deluxe 7,18.0,25.0,31.0,32.0,21.0,20.0,17.0,38.0,...,12.0,14.0,20.0,14.0,26.0,18.0,13.0,17.0,52.0,21.0
15,NaN,Original 1,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
16,NaN,Original 1+,4.0,5.0,3.0,3.0,1.0,2.0,3.0,6.0,...,1.0,NaN,4.0,5.0,6.0,5.0,5.0,2.0,8.0,5.0
17,NaN,Power 1,8.0,11.0,3.0,7.0,6.0,9.0,8.0,21.0,...,4.0,17.0,18.0,16.0,15.0,17.0,23.0,10.0,20.0,6.0
18,NaN,Power 7,19.0,11.0,9.0,20.0,18.0,17.0,20.0,18.0,...,28.0,18.0,16.0,28.0,19.0,31.0,24.0,13.0,21.0,NaN
19,NaN,Power Plus,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
20,NaN,Totaal,49.0,52.0,46.0,62.0,46.0,48.0,48.0,83.0,...,45.0,49.0,58.0,63.0,66.0,71.0,65.0,42.0,101.0,32.0
21,Aarhus,Deluxe 7,182.0,132.0,50.0,78.0,106.0,105.0,117.0,316.0,...,22.0,107.0,89.0,85.0,72.0,64.0,58.0,84.0,345.0,38.0
22,NaN,Original 1,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
23,NaN,Original 1+,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
24,NaN,Power 1,13.0,20.0,21.0,28.0,6.0,7.0,28.0,40.0,...,10.0,34.0,36.0,56.0,50.0,50.0,41.0,31.0,83.0,14.0
25,NaN,Power 7,23.0,31.0,31.0,27.0,23.0,50.0,40.0,45.0,...,9.0,32.0,39.0,89.0,61.0,96.0,51.0,59.0,72.0,11.0
26,NaN,Power Plus,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
27,NaN,Totaal,218.0,183.0,102.0,133.0,135.0,162.0,185.0,401.0,...,41.0,173.0,164.0,230.0,183.0,210.0,150.0,174.0,500.0,63.0
28,Amsterdam,Deluxe 7,1108.0,1581.0,1233.0,1176.0,1420.0,1654.0,1546.0,2554.0,...,580.0,1032.0,1429.0,1371.0,1369.0,1171.0,1059.0,1385.0,1945.0,255.0
29,NaN,Original 1,1031.0,1404.0,1072.0,994.0,1116.0,1190.0,1092.0,2092.0,...,594.0,1034.0,1332.0,1142.0,1149.0,1133.0,1132.0,1283.0,2080.0,247.0
30,NaN,Original 1+,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
31,NaN,Power 1,417.0,330.0,369.0,402.0,444.0,624.0,589.0,681.0,...,427.0,637.0,508.0,536.0,534.0,802.0,746.0,614.0,848.0,128.0
32,NaN,Power 7,366.0,458.0,579.0,533.0,629.0,494.0,426.0,411.0,...,286.0,251.0,434.0,623.0,488.0,291.0,408.0,599.0,347.0,20.0
33,NaN,Power Plus,NaN,NaN,NaN,NaN,NaN,NaN,NaN,8.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
34,NaN,Totaal,2922.0,3773.0,3253.0,3105.0,3609.0,3962.0,3653.0,5746.0,...,1887.0,2954.0,3703.0,3672.0,3540.0,3397.0,3345.0,3881.0,5220.0,650.0
35,Antwerp,Deluxe 7,102.0,143.0,126.0,141.0,115.0,135.0,111.0,170.0,...,58.0,101.0,130.0,126.0,149.0,128.0,93.0,132.0,136.0,38.0
36,NaN,Original 1,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
37,NaN,Original 1+,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
38,NaN,Power 1,92.0,64.0,102.0,93.0,97.0,98.0,102.0,92.0,...,29.0,50.0,39.0,58.0,51.0,41.0,32.0,42.0,47.0,9.0
39,NaN,Power 7,66.0,83.0,75.0,89.0,98.0,97.0,135.0,109.0,...,56.0,53.0,70.0,124.0,99.0,105.0,104.0,104.0,110.0,24.0
40,NaN,Power Plus,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,50.0,71.0,54.0,26.0,42.0,26.0,23.0,30.0,38.0,11.0
41,NaN,Totaal,260.0,290.0,303.0,323.0,310.0,330.0,348.0,371.0,...,193.0,275.0,293.0,334.0,341.0,300.0,252.0,308.0,331.0,82.0
42,Arnhem,Deluxe 7,57.0,34.0,38.0,26.0,45.0,29.0,34.0,104.0,...,25.0,40.0,41.0,43.0,42.0,35.0,29.0,28.0,138.0,23.0
43,NaN,Original 1,28.0,31.0,38.0,21.0,21.0,13.0,28.0,50.0,...,7.0,21.0,32.0,22.0,25.0,23.0,25.0,15.0,90.0,16.0
44,NaN,Original 1+,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
45,NaN,Power 1,16.0,19.0,16.0,15.0,20.0,33.0,35.0,28.0,...,28.0,39.0,24.0,32.0,36.0,41.0,26.0,46.0,38.0,NaN
46,NaN,Power 7,24.0,23.0,33.0,22.0,49.0,47.0,33.0,29.0,...,13.0,34.0,48.0,73.0,30.0,40.0,43.0,45.0,38.0,9.0
47,NaN,Power Plus,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
48,NaN,Totaal,125.0,107.0,125.0,84.0,135.0,122.0,130.0,211.0,...,73.0,134.0,145.0,170.0,133.0,139.0,123.0,134.0,304.0,48.0
49,Barcelona,Deluxe 7,89.0,113.0,109.0,113.0,144.0,89.0,99.0,154.0,...,48.0,138.0,169.0,121.0,139.0,179.0,166.0,156.0,181.0,133.0

# REPAIR DATASET

In [50]:

# Probeer met puntkomma als scheidingsteken
df = pd.read_csv("reparis _ services (2).csv")

print(df.head())
print(df.info())

                  LOAD_DATE_TIME WORLD_WIDE TERRITORY          COUNTRY  \
0  2025-09-05 15:17:46.832 +0200  worldwide   Benelux  The Netherlands
1  2025-09-05 15:17:46.832 +0200  worldwide   Benelux  The Netherlands
2  2025-09-05 15:17:46.832 +0200  worldwide   Benelux  The Netherlands
3  2025-09-05 15:17:46.832 +0200  worldwide   Benelux  The Netherlands
4  2025-09-05 15:17:46.832 +0200  worldwide   Benelux  The Netherlands

                  BUSINESS_UNIT                      LOCATION LOCATION_TYPE  \
0  Regional Warehouse Den Hoorn  Regional Warehouse Den Hoorn     Warehouse
1  Regional Warehouse Den Hoorn  Regional Warehouse Den Hoorn     Warehouse
2  Regional Warehouse Den Hoorn  Regional Warehouse Den Hoorn     Warehouse
3  Regional Warehouse Den Hoorn  Regional Warehouse Den Hoorn     Warehouse
4  Regional Warehouse Den Hoorn  Regional Warehouse Den Hoorn     Warehouse

                   SPECIFIC_LOCATION_TYPE  REPAIR_KEY REPAIR_TYPE_NAME  ...  \
0  Regional Warehouse Den Hoorn-Warehouse     1875488  MechanicsRepair  ...
1  Regional Warehouse Den Hoorn-Warehouse     1875488  MechanicsRepair  ...
2  Regional Warehouse Den Hoorn-Warehouse     1875488  MechanicsRepair  ...
3  Regional Warehouse Den Hoorn-Warehouse     1875488  MechanicsRepair  ...
4  Regional Warehouse Den Hoorn-Warehouse     1876649  MechanicsRepair  ...

              COMPLETED_ON ASSET_PART_NAME  PART_POSITION ASSET_SERVICE_TYPE  \
0  2021-02-26 10:55:49.107          Legacy            NaN            Replace
1  2021-02-26 10:55:49.107          Legacy            NaN            Replace
2  2021-02-26 10:55:49.107          Legacy            NaN             Repair
3  2021-02-26 10:55:49.107          Legacy            NaN            Replace
4  2021-03-02 08:31:02.667          Legacy            NaN             Repair

  ASSET_PART_CATEGORY BIKE_TYPE ASSET_COLOR_NAME              DATE_ACTIVE  \
0              Legacy    E-bike             Blue  2020-03-11 13:58:25.577
1              Legacy    E-bike             Blue  2020-03-11 13:58:25.577
2              Legacy    E-bike             Blue  2020-03-11 13:58:25.577
3              Legacy    E-bike             Blue  2020-03-11 13:58:25.577
4              Legacy    E-bike            Green                      NaN

      SUPPLIER HAS_TRACKER
0  Derby Cycle           0
1  Derby Cycle           0
2  Derby Cycle           0
3  Derby Cycle           0
4  Derby Cycle           0

[5 rows x 25 columns]
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 3836051 entries, 0 to 3836050
Data columns (total 25 columns):
 #   Column                  Dtype
---  ------                  -----
 0   LOAD_DATE_TIME          object
 1   WORLD_WIDE              object
 2   TERRITORY               object
 3   COUNTRY                 object
 4   BUSINESS_UNIT           object
 5   LOCATION                object
 6   LOCATION_TYPE           object
 7   SPECIFIC_LOCATION_TYPE  object
 8   REPAIR_KEY              int64
 9   REPAIR_TYPE_NAME        object
 10  REPAIR_STARTED_ON       object
 11  REPAIR_COMPLETED_ON     object
 12  ASSET_SERVICE_ID        int64
 13  ASSET_ID                object
 14  ASSET_CATEGORY_NAME     object
 15  COMPLETED_ON            object
 16  ASSET_PART_NAME         object
 17  PART_POSITION           object
 18  ASSET_SERVICE_TYPE      object
 19  ASSET_PART_CATEGORY     object
 20  BIKE_TYPE               object
 21  ASSET_COLOR_NAME        object
 22  DATE_ACTIVE             object
 23  SUPPLIER                object
 24  HAS_TRACKER             int64
dtypes: int64(3), object(22)
memory usage: 731.7+ MB
None

In [34]:

df = df.drop(["LOAD_DATE_TIME","WORLD_WIDE", 'TERRITORY','REPAIR_TYPE_NAME',"PART_POSITION", 'ASSET_SERVICE_ID','BIKE_TYPE','COMPLETED_ON','ASSET_COLOR_NAME','HAS_TRACKER'], axis=1)
#df
#df.dropna()
df

,COUNTRY,BUSINESS_UNIT,LOCATION,LOCATION_TYPE,SPECIFIC_LOCATION_TYPE,REPAIR_KEY,REPAIR_STARTED_ON,REPAIR_COMPLETED_ON,ASSET_ID,ASSET_CATEGORY_NAME,ASSET_PART_NAME,ASSET_SERVICE_TYPE,ASSET_PART_CATEGORY,DATE_ACTIVE,SUPPLIER
0,The Netherlands,Regional Warehouse Den Hoorn,Regional Warehouse Den Hoorn,Warehouse,Regional Warehouse Den Hoorn-Warehouse,1875488,2021-02-26 10:26:02.950,2021-02-26 10:55:49.107,DF2D6B56-CF7A-4EC9-A3F5-FEE51973B238,Power 7,Legacy,Replace,Legacy,2020-03-11 13:58:25.577,Derby Cycle
1,The Netherlands,Regional Warehouse Den Hoorn,Regional Warehouse Den Hoorn,Warehouse,Regional Warehouse Den Hoorn-Warehouse,1875488,2021-02-26 10:26:02.950,2021-02-26 10:55:49.107,DF2D6B56-CF7A-4EC9-A3F5-FEE51973B238,Power 7,Legacy,Replace,Legacy,2020-03-11 13:58:25.577,Derby Cycle
2,The Netherlands,Regional Warehouse Den Hoorn,Regional Warehouse Den Hoorn,Warehouse,Regional Warehouse Den Hoorn-Warehouse,1875488,2021-02-26 10:26:02.950,2021-02-26 10:55:49.107,DF2D6B56-CF7A-4EC9-A3F5-FEE51973B238,Power 7,Legacy,Repair,Legacy,2020-03-11 13:58:25.577,Derby Cycle
3,The Netherlands,Regional Warehouse Den Hoorn,Regional Warehouse Den Hoorn,Warehouse,Regional Warehouse Den Hoorn-Warehouse,1875488,2021-02-26 10:26:02.950,2021-02-26 10:55:49.107,DF2D6B56-CF7A-4EC9-A3F5-FEE51973B238,Power 7,Legacy,Replace,Legacy,2020-03-11 13:58:25.577,Derby Cycle
4,The Netherlands,Regional Warehouse Den Hoorn,Regional Warehouse Den Hoorn,Warehouse,Regional Warehouse Den Hoorn-Warehouse,1876649,2021-03-02 06:57:11.990,2021-03-02 08:31:02.667,EC0C92B3-EB53-4DC5-BDA4-FE53AD4E5D6D,Power 7,Legacy,Repair,Legacy,NaN,Derby Cycle
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
3836046,United Kingdom,London,London - Store - Shoreditch,Store,London-Store,1122247,2023-09-18 16:54:50.730,2023-09-18 16:55:29.417,ED50BE6D-0377-4802-9808-522D1C89B2A1,Power 7,Brake cable/hose,Adjust,Brakes,2023-06-01 15:12:59.310,RTE
3836047,United Kingdom,London,London - Store - Shoreditch,Store,London-Store,1122247,2023-09-18 16:54:50.730,2023-09-18 16:55:29.417,ED50BE6D-0377-4802-9808-522D1C89B2A1,Power 7,Chain,Lubricate,Drivetrain,2023-06-01 15:12:59.310,RTE
3836048,United Kingdom,London,London - Store - Shoreditch,Store,London-Store,1122247,2023-09-18 16:54:50.730,2023-09-18 16:55:29.417,ED50BE6D-0377-4802-9808-522D1C89B2A1,Power 7,Chain,Tension,Drivetrain,2023-06-01 15:12:59.310,RTE
3836049,United Kingdom,London,London - Store - Shoreditch,Store,London-Store,1122247,2023-09-18 16:54:50.730,2023-09-18 16:55:29.417,ED50BE6D-0377-4802-9808-522D1C89B2A1,Power 7,Bell,Replace,Handlebar,2023-06-01 15:12:59.310,RTE
3836050,United Kingdom,London,London - Store - Shoreditch,Store,London-Store,1122247,2023-09-18 16:54:50.730,2023-09-18 16:55:29.417,ED50BE6D-0377-4802-9808-522D1C89B2A1,Power 7,Gears,Adjust,Gears,2023-06-01 15:12:59.310,RTE

In [13]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1782224 entries, 0 to 1782223
Data columns (total 24 columns):
 #   Column                  Dtype
---  ------                  -----
 0   LOAD_DATE_TIME          object
 1   WORLD_WIDE              object
 2   TERRITORY               object
 3   COUNTRY                 object
 4   BUSINESS_UNIT           object
 5   LOCATION                object
 6   LOCATION_TYPE           object
 7   SPECIFIC_LOCATION_TYPE  object
 8   REPAIR_KEY              float64
 9   REPAIR_TYPE_NAME        object
 10  REPAIR_STARTED_ON       object
 11  REPAIR_COMPLETED_ON     object
 12  ASSET_SERVICE_ID        float64
 13  ASSET_ID                object
 14  ASSET_CATEGORY_NAME     object
 15  COMPLETED_ON            object
 16  ASSET_PART_NAME         object
 17  ASSET_SERVICE_TYPE      object
 18  ASSET_PART_CATEGORY     object
 19  BIKE_TYPE               object
 20  ASSET_COLOR_NAME        object
 21  DATE_ACTIVE             object
 22  SUPPLIER                object
 23  HAS_TRACKER             float64
dtypes: float64(3), object(21)
memory usage: 326.3+ MB

In [3]:
import pandas as pd

# Voorbeeld: frequentie per kolom
for col in df.columns:
    print(f"--- Kolom: {col} ---")
    print(df[col].value_counts())
    print()

--- Kolom: LOAD_DATE_TIME ---
LOAD_DATE_TIME
2025-09-05 15:17:46.832 +0200    3314381
2025-09-05 15:17:46.832 +020           1
Name: count, dtype: int64

--- Kolom: WORLD_WIDE ---
WORLD_WIDE
worldwide    3314381
Name: count, dtype: int64

--- Kolom: TERRITORY ---
TERRITORY
Benelux           1954068
Central Europe    1360313
Name: count, dtype: int64

--- Kolom: COUNTRY ---
COUNTRY
The Netherlands    1548464
Germany             699524
Belgium             405604
Denmark             364849
France              129487
United Kingdom       88720
Austria              28023
Spain                27732
Italy                21978
Name: count, dtype: int64

--- Kolom: BUSINESS_UNIT ---
BUSINESS_UNIT
Amsterdam                       663785
Regional Warehouse Belgium      349667
Regional Warehouse Den Hoorn    329979
Berlin                          291269
Copenhagen                      269900
                                 ...
Freiburg                             4
Nantes                               3
Ede - Wageningen                     2
Stuttgart                            1
Lübeck                               1
Name: count, Length: 72, dtype: int64

--- Kolom: LOCATION ---
LOCATION
Amsterdam - Warehouse Scharenburg                  427391
Regional warehouse Belgium                         349667
Regional Warehouse Den Hoorn                       329979
Copenhagen - Warehouse                             240119
Repair Centre Den Bosch                            200076
                                                    ...
Amsterdam - Warehouse Legmeerdijk 224                   1
Amsterdam - Warehouse Legmeerdijk 212                   1
Nantes Warehousehub                                     1
Amsterdam - Store Roetersstraat 17 - Intro Week         1
Rotterdam - Mariniersweg 76A - Intro Week               1
Name: count, Length: 182, dtype: int64

--- Kolom: LOCATION_TYPE ---
LOCATION_TYPE
Warehouse     2984353
Store          326892
Other            1386
Introweeks        867
Overflow          584
Hub               299
Name: count, dtype: int64

--- Kolom: SPECIFIC_LOCATION_TYPE ---
SPECIFIC_LOCATION_TYPE
Amsterdam-Warehouse                       611437
Regional Warehouse Belgium-Warehouse      349667
Regional Warehouse Den Hoorn-Warehouse    329979
Berlin-Warehouse                          260504
Copenhagen-Warehouse                      244118
                                           ...
Lübeck-Store                                   1
Nantes-Hub                                     1
Stuttgart-Store                                1
Maastricht-Introweeks                          1
Düsseldorf-Warehouse                           1
Name: count, Length: 139, dtype: int64

--- Kolom: REPAIR_KEY ---
REPAIR_KEY
597623.0     59
716047.0     52
3153457.0    52
2939738.0    52
2987147.0    49
             ..
2768297.0     1
2769561.0     1
2789449.0     1
2776191.0     1
2374224.0     1
Name: count, Length: 454622, dtype: int64

--- Kolom: REPAIR_TYPE_NAME ---
REPAIR_TYPE_NAME
MechanicsRepair    3089328
RetailRepair        225053
Name: count, dtype: int64

--- Kolom: REPAIR_STARTED_ON ---
REPAIR_STARTED_ON
2020-09-22 10:00:00.000    381
2020-09-24 10:00:00.000    265
2020-09-23 10:00:00.000    264
2020-09-30 10:00:00.000    204
2020-10-01 10:00:00.000    184
                          ...
2021-03-22 17:54:03.550      1
2021-03-11 13:30:44.887      1
2022-05-13 08:04:23.547      1
2023-01-09 13:27:30.310      1
2022-12-09 15:42:52.917      1
Name: count, Length: 446470, dtype: int64

--- Kolom: REPAIR_COMPLETED_ON ---
REPAIR_COMPLETED_ON
2020-09-22 10:06:00.000    381
2020-09-24 10:06:00.000    265
2020-09-23 10:06:00.000    264
2020-09-30 10:06:00.000    204
2020-10-01 10:06:00.000    184
                          ...
2021-03-11 13:31:03.233      1
2022-05-13 08:04:32.147      1
2024-08-02 13:57:02.393      1
2024-08-03 15:17:19.673      1
2021-08-25 10:43:02.610      1
Name: count, Length: 446568, dtype: int64

--- Kolom: ASSET_SERVICE_ID ---
ASSET_SERVICE_ID
4922181.0    1
5393511.0    1
5393504.0    1
5393509.0    1
5393507.0    1
            ..
9352004.0    1
9351999.0    1
9352001.0    1
9352000.0    1
1305841.0    1
Name: count, Length: 3314381, dtype: int64

--- Kolom: ASSET_ID ---
ASSET_ID
A3DFB8F8-3F3E-40D0-91B5-17BCB41CEB96    250
E32A5FA6-7702-492D-90A1-C0A2B0603CF9    239
C0182FCD-9FFB-4F28-A336-0845591C3E16    238
42804516-8B7F-45CE-AC2D-92F128EAC93D    238
1E2D31A5-0220-4C45-9FFF-F8C3D88D5161    237
                                       ...
3260BACB-A134-4AE9-998F-D7026E7B0E8E      1
E5A6B8C0-A343-4053-A003-D87E83B83038      1
05825E77-A51F-4B9A-B60C-EEC5716048A8      1
5BE76644-C801-48D0-88EA-BFD95CE6E247      1
1D5494E4-7541-4C75-A34E-CB4C808F1247      1
Name: count, Length: 79224, dtype: int64

--- Kolom: ASSET_CATEGORY_NAME ---
ASSET_CATEGORY_NAME
Power 7       2370539
Power 1        866176
Power Plus      77666
Name: count, dtype: int64

--- Kolom: COMPLETED_ON ---
COMPLETED_ON
2020-09-22 10:06:00.000    381
2020-09-24 10:06:00.000    265
2020-09-23 10:06:00.000    264
2020-09-30 10:06:00.000    204
2020-10-01 10:06:00.000    184
                          ...
2021-03-11 13:31:03.233      1
2022-05-13 08:04:32.147      1
2024-08-02 13:57:02.393      1
2024-08-03 15:17:19.673      1
2021-08-25 10:43:02.610      1
Name: count, Length: 446568, dtype: int64

--- Kolom: ASSET_PART_NAME ---
ASSET_PART_NAME
Chain               520209
Brake cable/hose    223786
Kickstand           202152
Wheel               190366
Frame lock          181405
                     ...
Shimmy damper            6
Engine bracket           4
Magnet                   2
Battery cover            2
Battery clip             2
Name: count, Length: 72, dtype: int64

--- Kolom: PART_POSITION ---
PART_POSITION
Front         635762
Rear          342529
Both/All      132425
Left           24176
Right          23929
Rear left         50
Rear right        49
Name: count, dtype: int64

--- Kolom: ASSET_SERVICE_TYPE ---
ASSET_SERVICE_TYPE
Replace      983831
Lubricate    645223
Adjust       486907
Repair       329919
Grease       268919
Tension      245066
True         149394
Tighten      138329
Pump          26640
Add new       22732
Sticker       16885
Bleed           536
Name: count, dtype: int64

--- Kolom: ASSET_PART_CATEGORY ---
ASSET_PART_CATEGORY
Drivetrain    714525
Wheel         434116
Handlebar     388777
Lock          339543
Brakes        294429
Frame         278971
Saddle        193079
Gears         174883
Electrics     149142
Light         133958
Fenders       133802
Legacy         79156
Name: count, dtype: int64

--- Kolom: BIKE_TYPE ---
BIKE_TYPE
E-bike    3314381
Name: count, dtype: int64

--- Kolom: ASSET_COLOR_NAME ---
ASSET_COLOR_NAME
Green     870911
Black     619816
Blue      558544
Gray      512280
Beige     428484
Red       321392
Orange      2954
Name: count, dtype: int64

--- Kolom: DATE_ACTIVE ---
DATE_ACTIVE
2024-06-07 08:58:14.067    371
2022-04-04 15:53:44.740    348
2024-07-31 13:33:09.933    343
2023-07-11 14:20:41.680    342
2025-04-10 13:48:10.930    338
                          ...
2025-01-29 16:00:56.867      1
2021-03-15 14:45:09.377      1
2025-05-15 11:21:45.647      1
2024-11-11 16:02:53.520      1
2025-07-08 14:01:45.117      1
Name: count, Length: 57838, dtype: int64

--- Kolom: SUPPLIER ---
SUPPLIER
Baltik Vairas     2275824
Gazelle Dieren     685381
RTE                288590
Derby Cycle         63854
Union                 732
Name: count, dtype: int64

--- Kolom: HAS_TRACKER ---
HAS_TRACKER
0.0    3314381
Name: count, dtype: int64

# readytogo

In [57]:
import pandas as pd

# Probeer met puntkomma als scheidingsteken
df = pd.read_csv("Metric Store - ReadyToGo Bikes.csv", encoding="latin1", sep=";")
df["Geographical Indicator"] = df["Geographical Indicator"].ffill()
df_Readytogo = df[df["Colour Category"] == "Power 7"]
df_Readytogo = df_Readytogo.fillna(0)

In [58]:
df = pd.read_excel("Metric Store - InUse Bikes.xlsx")
df["Geographical Indicator"] = df["Geographical Indicator"].ffill()
df_Inuse = df[df["Colour Category"] == "Power 7"]
df_Inuse = df_Inuse.fillna(0)

In [59]:
df = pd.read_excel("Metric Store - Inventory (1).xlsx")
df["Geographical Indicator"] = df["Geographical Indicator"].ffill()
df_Inventory = df[df["Colour Category"] == "Power 7"]
df_Inventory = df_Inventory.fillna(0)

In [60]:
df = pd.read_excel("Metric Store - Broken Bikes (1).xlsx")
df["Geographical Indicator"] = df["Geographical Indicator"].ffill()
df_Broken = df[df["Colour Category"] == "Power 7"]
df_Broken = df_Broken.fillna(0)

In [61]:
df = pd.read_excel("Metric Store - Subscriptions (1).xlsx")
df["Geographical Indicator"] = df["Geographical Indicator"].ffill()
df_Subscriptions = df[df["Colour Category"] == "Power 7"]
df_Subscriptions = df_Subscriptions.fillna(0)

In [62]:
df = pd.read_excel("Metric Store - Missing Bikes.xlsx")
df["Geographical Indicator"] = df["Geographical Indicator"].ffill()
df_Missing = df[df["Colour Category"] == "Power 7"]
df_Missing = df_Missing.fillna(0)

In [63]:
import pandas as pd

key_cols = ["Geographical Indicator", "Colour Category"]
month_cols = [c for c in df_Readytogo.columns if c not in key_cols]

df_list = [df_Readytogo, df_Broken, df_Inventory, df_Inuse, df_Subscriptions,df_Missing]
suffixes = ["Readytogo", "Broken", "Inventory", "Inuse","Subscriptions","Missing"]

# Kopieer key_cols naar de nieuwe DataFrame
df_combined = df_Readytogo[key_cols].copy()

# Voeg kolommen per maand toe, interleaved
new_cols = {}
for m in month_cols:
    for df_src, suffix in zip(df_list, suffixes):
        new_cols[f"{m}_{suffix}"] = df_src[m]

# Voeg alle kolommen in één keer toe
df_combined = pd.concat([df_combined, pd.DataFrame(new_cols)], axis=1)

In [70]:
df_combined

,Geographical Indicator,Colour Category,'23-01_Readytogo,'23-01_Broken,'23-01_Inventory,'23-01_Inuse,'23-01_Subscriptions,'23-01_Missing,'23-02_Readytogo,'23-02_Broken,...,'25-08_Inventory,'25-08_Inuse,'25-08_Subscriptions,'25-08_Missing,'25-09_Readytogo,'25-09_Broken,'25-09_Inventory,'25-09_Inuse,'25-09_Subscriptions,'25-09_Missing
4,50/50 Leger des Heils,Power 7,0,0.0,0.0,0.0,0.0,0.0,0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
11,Aachen,Power 7,0,0.0,0.0,1.0,0.0,4.0,0,0.0,...,0.0,0.0,0.0,4.0,0.0,0.0,0.0,0.0,0.0,0.0
18,Aalborg,Power 7,"35,00",7.0,0.0,115.0,117.0,6.0,"32,00",17.0,...,0.0,207.0,207.0,23.0,0.0,0.0,0.0,0.0,0.0,0.0
25,Aarhus,Power 7,"23,00",22.0,0.0,162.0,164.0,12.0,"29,00",11.0,...,0.0,536.0,551.0,39.0,0.0,0.0,0.0,0.0,0.0,0.0
32,Amsterdam,Power 7,"621,00",793.0,59.0,3022.0,3246.0,694.0,"311,00",928.0,...,0.0,5392.0,5581.0,1035.0,0.0,0.0,0.0,0.0,0.0,0.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
494,Toulouse,Power 7,"9,00",22.0,0.0,104.0,118.0,10.0,"35,00",19.0,...,0.0,0.0,0.0,23.0,0.0,0.0,0.0,0.0,0.0,0.0
501,Utrecht,Power 7,"76,00",45.0,0.0,556.0,574.0,95.0,"58,00",26.0,...,0.0,1365.0,1395.0,190.0,0.0,0.0,0.0,0.0,0.0,0.0
508,Vienna,Power 7,"214,00",278.0,0.0,549.0,598.0,46.0,"193,00",272.0,...,0.0,185.0,194.0,116.0,0.0,0.0,0.0,0.0,0.0,0.0
515,Wolfsburg,Power 7,0,0.0,0.0,1.0,1.0,1.0,0,0.0,...,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0
522,Zwolle,Power 7,0,2.0,0.0,33.0,31.0,1.0,0,4.0,...,0.0,0.0,0.0,2.0,0.0,0.0,0.0,0.0,0.0,0.0

In [72]:
import pandas as pd

# Functie om strings naar float te converteren
def to_float(val):
    if pd.isna(val):
        return 0.0
    val = str(val)
    val = val.replace('.', '')  # verwijder punten als duizendtallen
    val = val.replace(',', '.') # vervang komma door punt
    try:
        return float(val)
    except ValueError:
        return 0.0  # fallback voor rare tekens

# Pas dit toe op alle numerieke kolommen vanaf de derde
for col in df_combined.columns[2:]:
    df_combined[col] = df_combined[col].apply(to_float)

# Bereken totaal per numerieke kolom
num_cols = df_combined.columns[2:]
totaal = pd.DataFrame(df_combined[num_cols].sum()).T
totaal["Geographical Indicator"] = "Totaal"
totaal["Colour Category"] = ""
totaal = totaal[df_combined.columns]

# Voeg totaalregel onderaan
df_combined_with_total = pd.concat([df_combined, totaal], ignore_index=True)

print(df_combined_with_total.tail())

   Geographical Indicator Colour Category  '23-01_Readytogo  '23-01_Broken  \
71                Utrecht         Power 7             760.0          450.0
72                 Vienna         Power 7            2140.0         2780.0
73              Wolfsburg         Power 7               0.0            0.0
74                 Zwolle         Power 7               0.0           20.0
75                 Totaal                           44460.0        79120.0

    '23-01_Inventory  '23-01_Inuse  '23-01_Subscriptions  '23-01_Missing  \
71               0.0        5560.0                5740.0           950.0
72               0.0        5490.0                5980.0           460.0
73               0.0          10.0                  10.0            10.0
74               0.0         330.0                 310.0            10.0
75           72970.0      193680.0              207210.0         39200.0

    '23-02_Readytogo  '23-02_Broken  ...  '25-08_Inventory  '25-08_Inuse  \
71             580.0          260.0  ...               0.0       13650.0
72            1930.0         2720.0  ...               0.0        1850.0
73               0.0            0.0  ...               0.0           0.0
74               0.0           40.0  ...               0.0           0.0
75           41960.0        78300.0  ...              20.0      263180.0

    '25-08_Subscriptions  '25-08_Missing  '25-09_Readytogo  '25-09_Broken  \
71               13950.0          1900.0               0.0            0.0
72                1940.0          1160.0               0.0            0.0
73                   0.0            10.0               0.0            0.0
74                   0.0            20.0               0.0            0.0
75              271920.0         76920.0               0.0            0.0

    '25-09_Inventory  '25-09_Inuse  '25-09_Subscriptions  '25-09_Missing
71               0.0           0.0                   0.0             0.0
72               0.0           0.0                   0.0             0.0
73               0.0           0.0                   0.0             0.0
74               0.0           0.0                   0.0             0.0
75               0.0           0.0                   0.0             0.0

[5 rows x 200 columns]

In [73]:
df_combined_with_total

,Geographical Indicator,Colour Category,'23-01_Readytogo,'23-01_Broken,'23-01_Inventory,'23-01_Inuse,'23-01_Subscriptions,'23-01_Missing,'23-02_Readytogo,'23-02_Broken,...,'25-08_Inventory,'25-08_Inuse,'25-08_Subscriptions,'25-08_Missing,'25-09_Readytogo,'25-09_Broken,'25-09_Inventory,'25-09_Inuse,'25-09_Subscriptions,'25-09_Missing
0,50/50 Leger des Heils,Power 7,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
1,Aachen,Power 7,0.0,0.0,0.0,10.0,0.0,40.0,0.0,0.0,...,0.0,0.0,0.0,40.0,0.0,0.0,0.0,0.0,0.0,0.0
2,Aalborg,Power 7,350.0,70.0,0.0,1150.0,1170.0,60.0,320.0,170.0,...,0.0,2070.0,2070.0,230.0,0.0,0.0,0.0,0.0,0.0,0.0
3,Aarhus,Power 7,230.0,220.0,0.0,1620.0,1640.0,120.0,290.0,110.0,...,0.0,5360.0,5510.0,390.0,0.0,0.0,0.0,0.0,0.0,0.0
4,Amsterdam,Power 7,6210.0,7930.0,590.0,30220.0,32460.0,6940.0,3110.0,9280.0,...,0.0,53920.0,55810.0,10350.0,0.0,0.0,0.0,0.0,0.0,0.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
71,Utrecht,Power 7,760.0,450.0,0.0,5560.0,5740.0,950.0,580.0,260.0,...,0.0,13650.0,13950.0,1900.0,0.0,0.0,0.0,0.0,0.0,0.0
72,Vienna,Power 7,2140.0,2780.0,0.0,5490.0,5980.0,460.0,1930.0,2720.0,...,0.0,1850.0,1940.0,1160.0,0.0,0.0,0.0,0.0,0.0,0.0
73,Wolfsburg,Power 7,0.0,0.0,0.0,10.0,10.0,10.0,0.0,0.0,...,0.0,0.0,0.0,10.0,0.0,0.0,0.0,0.0,0.0,0.0
74,Zwolle,Power 7,0.0,20.0,0.0,330.0,310.0,10.0,0.0,40.0,...,0.0,0.0,0.0,20.0,0.0,0.0,0.0,0.0,0.0,0.0
75,Totaal,,44460.0,79120.0,72970.0,193680.0,207210.0,39200.0,41960.0,78300.0,...,20.0,263180.0,271920.0,76920.0,0.0,0.0,0.0,0.0,0.0,0.0

In [24]:
df.head(50)

,Geographical Indicator,Colour Category,'23-01,'23-02,'23-03,'23-04,'23-05,'23-06,'23-07,'23-08,...,'24-12,'25-01,'25-02,'25-03,'25-04,'25-05,'25-06,'25-07,'25-08,'25-09
4,50/50 Leger des Heils,Power 7,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
11,Aachen,Power 7,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
18,Aalborg,Power 7,"35,00","32,00","21,00","11,00","26,00","55,00","42,00","32,00",...,"16,00","13,00","13,00","24,00","36,00","15,00","29,00","31,00","34,00",NaN
25,Aarhus,Power 7,"23,00","29,00","23,00","14,00","24,00","22,00","14,00","14,00",...,"17,00","40,00","30,00","14,00","30,00","41,00","11,00","26,00","15,00",NaN
32,Amsterdam,Power 7,"621,00","311,00","288,00","405,00","334,00","282,00","249,00","705,00",...,"1.393,00","1.207,00","917,00","327,00","341,00","644,00","425,00","394,00","163,00",NaN
39,Antwerp,Power 7,"28,00","24,00","39,00","19,00","26,00","35,00","24,00","39,00",...,"24,00","25,00","16,00","22,00","26,00","22,00","19,00","24,00","23,00",NaN
46,Arnhem,Power 7,"12,00","7,00","8,00","16,00","9,00","13,00","15,00","10,00",...,"14,00","13,00","17,00","11,00","20,00","11,00","16,00","16,00","12,00",NaN
53,Barcelona,Power 7,"89,00","117,00","166,00","236,00","198,00","276,00","280,00","222,00",...,"85,00","46,00","68,00","45,00","38,00","52,00","28,00","28,00","34,00",NaN
60,Barneveld (distributie),Power 7,"45,00","36,00","36,00","36,00","36,00","32,00","36,00","46,00",...,"328,00","61,00","107,00","362,00","190,00","247,00","199,00","101,00","123,00",NaN
67,Berlin,Power 7,"429,00","381,00","435,00","249,00","173,00","223,00","156,00","202,00",...,"342,00","375,00","438,00","397,00","279,00","175,00","156,00","169,00","231,00",NaN
74,Bike Repair Shop Sittard,Power 7,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,"70,00",NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
81,Bonn,Power 7,"9,00","4,00","13,00","20,00","18,00","15,00","16,00","13,00",...,"16,00","8,00","11,00","9,00","19,00","19,00","20,00","21,00","15,00",NaN
88,Braunschweig,Power 7,"38,00","30,00","17,00","8,00","13,00","13,00","21,00","16,00",...,"15,00","14,00","24,00","22,00","14,00","12,00","7,00","18,00","20,00",NaN
95,Breda,Power 7,"11,00","13,00","15,00","16,00","15,00","8,00","14,00","9,00",...,"11,00","15,00","13,00","14,00","5,00","14,00","11,00","15,00","24,00",NaN
102,Bremen,Power 7,"9,00","4,00","3,00","6,00","8,00","8,00","17,00","10,00",...,"17,00","13,00","25,00","11,00","23,00","7,00","12,00","18,00","18,00",NaN
109,Brussel,Power 7,"26,00","27,00","37,00","55,00","59,00","75,00","60,00","75,00",...,"28,00","38,00","32,00","16,00","13,00","3,00","14,00","23,00","22,00",NaN
116,Cologne,Power 7,"108,00","132,00","178,00","166,00","88,00","157,00","106,00","106,00",...,"196,00","320,00","340,00","204,00","91,00","56,00","102,00","168,00","147,00",NaN
123,Copenhagen,Power 7,"68,00","45,00","72,00","47,00","65,00","103,00","107,00","223,00",...,"421,00","387,00","271,00","171,00","168,00","107,00","187,00","174,00","194,00",NaN
130,Delft,Power 7,"12,00","9,00","4,00","6,00","7,00","3,00","6,00","7,00",...,"17,00","13,00","12,00","11,00","8,00","8,00","2,00","11,00","11,00",NaN
137,Den Bosch,Power 7,NaN,NaN,"1,00","1,00","1,00",NaN,NaN,NaN,...,NaN,"2,00","2,00",NaN,NaN,NaN,NaN,NaN,NaN,NaN
144,Den Haag,Power 7,"12,00","15,00","13,00","9,00","5,00","16,00","22,00","27,00",...,"18,00","18,00","20,00","8,00","20,00","16,00","10,00","15,00","22,00",NaN
151,Dresden,Power 7,"1,00","1,00","1,00","1,00","1,00","1,00","1,00","1,00",...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
158,Düsseldorf,Power 7,"10,00","18,00","21,00","25,00","28,00","16,00","17,00","33,00",...,"24,00","20,00","30,00","38,00","25,00","23,00","53,00","40,00","37,00",NaN
165,Ede - Wageningen,Power 7,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
172,Eindhoven,Power 7,"11,00","9,00","25,00","22,00","17,00","27,00","24,00","32,00",...,"27,00","22,00","22,00","18,00","28,00","17,00","23,00","20,00","15,00",NaN
179,Enschede,Power 7,"3,00","13,00","14,00","12,00","13,00","15,00","7,00","11,00",...,"29,00","23,00","7,00","6,00","19,00","19,00","15,00","23,00","7,00",NaN
186,Frankfurt,Power 7,"9,00","5,00","13,00","8,00","30,00","18,00","21,00","24,00",...,"20,00","36,00","30,00","25,00","21,00","16,00","18,00","30,00","21,00",NaN
193,Freiburg,Power 7,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
200,Gent,Power 7,"24,00","19,00","24,00","15,00","25,00","27,00","15,00","19,00",...,"14,00","13,00","17,00","5,00","5,00","24,00","11,00","21,00","18,00",NaN
207,Göttingen,Power 7,"6,00","10,00","16,00","10,00","7,00","13,00","13,00","9,00",...,"5,00","5,00","9,00","7,00","6,00","7,00","6,00","13,00","18,00",NaN
214,Groningen,Power 7,"19,00","15,00","16,00","18,00","17,00","28,00","16,00","16,00",...,"8,00","10,00","16,00","15,00","9,00","12,00","14,00","18,00","14,00",NaN
221,Haarlem,Power 7,"28,00","30,00","29,00","15,00","10,00","15,00","12,00","15,00",...,"17,00","14,00","14,00","3,00","14,00","22,00","10,00","17,00","14,00",NaN
228,Halle,Power 7,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
235,Hamburg,Power 7,"420,00","390,00","333,00","191,00","161,00","225,00","213,00","145,00",...,"562,00","681,00","686,00","462,00","227,00","71,00","121,00","133,00","128,00",NaN
242,Hannover,Power 7,"99,00","90,00","71,00","31,00","104,00","62,00","40,00","50,00",...,"254,00","223,00","237,00","155,00","73,00","40,00","95,00","88,00","53,00",NaN
249,Heidelberg,Power 7,"11,00","8,00","1,00","1,00",NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
256,Karlsruhe,Power 7,"97,00","107,00","127,00","88,00","60,00","73,00","101,00","90,00",...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
263,Kiel,Power 7,"25,00","20,00","19,00","16,00","12,00","21,00","22,00","21,00",...,"24,00","12,00","17,00","10,00","7,00","23,00","20,00","21,00","26,00",NaN
270,Leeuwarden,Power 7,"21,00","24,00","18,00","13,00","15,00","36,00","29,00","27,00",...,"32,00","42,00","30,00","4,00","14,00","16,00","21,00","26,00","12,00",NaN
277,Leiden,Power 7,"19,00","18,00","20,00","24,00","26,00","28,00","19,00","18,00",...,"30,00","13,00","20,00","4,00","10,00","32,00","11,00","15,00","24,00",NaN
284,Leipzig,Power 7,"113,00","142,00","123,00","92,00","65,00","59,00","79,00","66,00",...,"7,00","9,00","13,00","4,00","22,00","23,00","12,00","20,00","17,00",NaN
291,Leuven,Power 7,"23,00","17,00","18,00","23,00","30,00","19,00","19,00","22,00",...,"17,00","20,00","10,00","15,00","19,00","3,00","15,00","18,00","11,00",NaN
298,London,Power 7,"68,00","53,00","94,00","124,00","96,00","39,00","87,00","80,00",...,"219,00","236,00","256,00","223,00","135,00","139,00","84,00","107,00","87,00",NaN
305,Lübeck,Power 7,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
312,Lyon,Power 7,"43,00","43,00","52,00","24,00","10,00","10,00","10,00","10,00",...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
319,Maastricht,Power 7,"20,00","32,00","22,00","22,00","26,00","14,00","14,00","17,00",...,"13,00","14,00","1,00","7,00","29,00","21,00","5,00","10,00","10,00",NaN
326,Mainz-Wiesbaden,Power 7,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
333,Mechelen,Power 7,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
340,Milan,Power 7,"186,00","179,00","39,00","83,00","40,00","3,00",NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
347,Munich,Power 7,"113,00","140,00","125,00","186,00","205,00","159,00","119,00","77,00",...,"229,00","245,00","252,00","198,00","97,00","67,00","40,00","78,00","53,00",NaN

In [17]:
import pandas as pd

# Voorbeeld: frequentie per kolom
for col in df.columns:
    print(f"--- Kolom: {col} ---")
    print(df[col].value_counts())
    print()

--- Kolom: Geographical Indicator ---
Geographical Indicator
50/50 Leger des Heils    1
Milan                    1
Osnabrück                1
Oldenburg                1
Odense                   1
                        ..
Eindhoven                1
Ede - Wageningen         1
Düsseldorf               1
Dresden                  1
Eindtotaal               1
Name: count, Length: 76, dtype: int64

--- Kolom: Colour Category ---
Colour Category
Totaal         76
Deluxe 7       75
Original 1     75
Original 1+    75
Power 1        75
Power 7        75
Power Plus     75
Name: count, dtype: int64

--- Kolom: '23-01 ---
'23-01
1,00         8
10,00        8
9,00         8
11,00        7
19,00        6
            ..
86,00        1
116,00       1
71,00        1
69,00        1
54.460,00    1
Name: count, Length: 167, dtype: int64

--- Kolom: '23-02 ---
'23-02
1,00         11
16,00         7
27,00         7
35,00         6
24,00         6
             ..
113,00        1
76,00         1
108,00        1
19,00         1
53.631,00     1
Name: count, Length: 166, dtype: int64

--- Kolom: '23-03 ---
'23-03
1,00         16
19,00         7
13,00         6
17,00         6
20,00         5
             ..
216,00        1
61,00         1
85,00         1
104,00        1
56.478,00     1
Name: count, Length: 169, dtype: int64

--- Kolom: '23-04 ---
'23-04
1,00         17
16,00         7
15,00         7
17,00         6
11,00         6
             ..
122,00        1
59,00         1
125,00        1
309,00        1
53.787,00     1
Name: count, Length: 170, dtype: int64

--- Kolom: '23-05 ---
'23-05
1,00         19
19,00         7
17,00         7
13,00         6
2,00          5
             ..
22,00         1
3,00          1
499,00        1
86,00         1
50.698,00     1
Name: count, Length: 158, dtype: int64

--- Kolom: '23-06 ---
'23-06
1,00         9
13,00        6
8,00         6
16,00        6
39,00        5
            ..
338,00       1
560,00       1
157,00       1
95,00        1
51.504,00    1
Name: count, Length: 159, dtype: int64

--- Kolom: '23-07 ---
'23-07
19,00        8
12,00        6
7,00         6
15,00        5
17,00        5
            ..
4,00         1
33,00        1
8,00         1
45,00        1
57.445,00    1
Name: count, Length: 165, dtype: int64

--- Kolom: '23-08 ---
'23-08
1,00         7
11,00        6
26,00        5
13,00        5
21,00        5
            ..
1.652,00     1
223,00       1
215,00       1
1.084,00     1
49.825,00    1
Name: count, Length: 163, dtype: int64

--- Kolom: '23-09 ---
'23-09
19,00        7
1,00         7
13,00        6
29,00        6
18,00        6
            ..
198,00       1
38,00        1
1.574,00     1
196,00       1
37.845,00    1
Name: count, Length: 153, dtype: int64

--- Kolom: '23-10 ---
'23-10
36,00        7
1,00         7
10,00        7
11,00        6
30,00        6
            ..
37,00        1
94,00        1
4,00         1
68,00        1
39.380,00    1
Name: count, Length: 156, dtype: int64

--- Kolom: '23-11 ---
'23-11
1,00         10
24,00         7
32,00         6
16,00         6
26,00         6
             ..
138,00        1
221,00        1
271,00        1
1.315,00      1
42.936,00     1
Name: count, Length: 157, dtype: int64

--- Kolom: '23-12 ---
'23-12
10,00        8
1,00         7
22,00        6
9,00         6
14,00        6
            ..
89,00        1
2.179,00     1
351,00       1
1.596,00     1
48.314,00    1
Name: count, Length: 145, dtype: int64

--- Kolom: '24-01 ---
'24-01
13,00        8
12,00        7
7,00         7
39,00        6
23,00        5
            ..
106,00       1
32,00        1
1.563,00     1
147,00       1
49.662,00    1
Name: count, Length: 159, dtype: int64

--- Kolom: '24-02 ---
'24-02
4,00         7
20,00        6
29,00        5
9,00         5
26,00        5
            ..
522,00       1
581,00       1
125,00       1
141,00       1
49.376,00    1
Name: count, Length: 161, dtype: int64

--- Kolom: '24-03 ---
'24-03
17,00        10
1,00          8
4,00          5
3,00          5
10,00         5
             ..
82,00         1
114,00        1
27,00         1
124,00        1
50.076,00     1
Name: count, Length: 150, dtype: int64

--- Kolom: '24-04 ---
'24-04
1,00         8
25,00        7
15,00        6
14,00        5
11,00        5
            ..
617,00       1
81,00        1
500,00       1
107,00       1
49.381,00    1
Name: count, Length: 149, dtype: int64

--- Kolom: '24-05 ---
'24-05
16,00        7
1,00         7
23,00        6
21,00        6
11,00        6
            ..
108,00       1
173,00       1
66,00        1
44,00        1
48.919,00    1
Name: count, Length: 157, dtype: int64

--- Kolom: '24-06 ---
'24-06
12,00        8
18,00        7
1,00         7
15,00        7
14,00        6
            ..
227,00       1
255,00       1
937,00       1
617,00       1
53.286,00    1
Name: count, Length: 159, dtype: int64

--- Kolom: '24-07 ---
'24-07
12,00        8
11,00        7
14,00        7
2,00         6
17,00        6
            ..
169,00       1
159,00       1
171,00       1
3,00         1
60.682,00    1
Name: count, Length: 159, dtype: int64

--- Kolom: '24-08 ---
'24-08
9,00         9
20,00        8
17,00        6
6,00         6
10,00        6
            ..
952,00       1
93,00        1
24,00        1
95,00        1
49.152,00    1
Name: count, Length: 152, dtype: int64

--- Kolom: '24-09 ---
'24-09
21,00        8
17,00        7
30,00        6
19,00        5
26,00        5
            ..
44,00        1
148,00       1
32,00        1
64,00        1
39.188,00    1
Name: count, Length: 149, dtype: int64

--- Kolom: '24-10 ---
'24-10
12,00        7
20,00        7
27,00        5
18,00        5
40,00        4
            ..
1.649,00     1
264,00       1
295,00       1
266,00       1
42.907,00    1
Name: count, Length: 158, dtype: int64

--- Kolom: '24-11 ---
'24-11
9,00         7
32,00        6
25,00        6
14,00        5
16,00        5
            ..
74,00        1
86,00        1
2.108,00     1
330,00       1
46.914,00    1
Name: count, Length: 157, dtype: int64

--- Kolom: '24-12 ---
'24-12
16,00        6
17,00        6
24,00        5
28,00        4
15,00        4
            ..
442,00       1
586,00       1
1.481,00     1
1.653,00     1
54.186,00    1
Name: count, Length: 168, dtype: int64

--- Kolom: '25-01 ---
'25-01
13,00        10
9,00          6
21,00         5
1,00          5
8,00          5
             ..
372,00        1
688,00        1
1.498,00      1
1.697,00      1
53.673,00     1
Name: count, Length: 165, dtype: int64

--- Kolom: '25-02 ---
'25-02
25,00        7
1,00         6
16,00        6
20,00        4
9,00         4
            ..
581,00       1
1.294,00     1
1.642,00     1
340,00       1
49.680,00    1
Name: count, Length: 154, dtype: int64

--- Kolom: '25-03 ---
'25-03
22,00        11
11,00         8
14,00         5
18,00         5
9,00          4
             ..
171,00        1
152,00        1
456,00        1
937,00        1
44.125,00     1
Name: count, Length: 157, dtype: int64

--- Kolom: '25-04 ---
'25-04
14,00        8
20,00        7
23,00        7
12,00        6
19,00        6
            ..
168,00       1
134,00       1
268,00       1
348,00       1
35.693,00    1
Name: count, Length: 151, dtype: int64

--- Kolom: '25-05 ---
'25-05
14,00        7
11,00        6
16,00        6
12,00        5
15,00        5
            ..
128,00       1
148,00       1
1.726,00     1
68,00        1
29.246,00    1
Name: count, Length: 145, dtype: int64

--- Kolom: '25-06 ---
'25-06
12,00        8
14,00        7
15,00        5
28,00        5
16,00        5
            ..
604,00       1
504,00       1
61,00        1
235,00       1
30.069,00    1
Name: count, Length: 152, dtype: int64

--- Kolom: '25-07 ---
'25-07
12,00        9
18,00        7
20,00        6
92,00        5
15,00        5
            ..
64,00        1
24,00        1
100,00       1
217,00       1
33.025,00    1
Name: count, Length: 148, dtype: int64

--- Kolom: '25-08 ---
'25-08
11,00        7
22,00        6
10,00        6
16,00        5
12,00        5
            ..
28,00        1
1.069,00     1
194,00       1
158,00       1
21.927,00    1
Name: count, Length: 151, dtype: int64

--- Kolom: '25-09 ---
Series([], Name: count, dtype: int64)

# vragen

In [52]:
bij alle losse documeten wat houden ze in, kan hier een legenda voor worden gemaakt en dit ook voor de reparatie bestand?

Object `bestand` not found.

is repair_key of assed_id de id per fiets zodat je verschillende reparaties aan elkaar kan koppelen.

Beschikbaarheid verhogen
- ReadytoGo bikes doelfactor (wat je wilt voorspellen)
- in use/subscripsion en missing bikes,broken bikes ( hiermee kan je zien hoeveel er gebruikt worden en hoeveel je er kwijt raakt)
- 
→ genoeg ReadyToGo Bikes hebben op elk moment, ondanks reparaties of missende fietsen.

→ voorspellen hoeveel fietsen per locatie nodig zijn.

Onderhoud efficiënter maken

→ door Warehouse Repairs vs. Store Repairs te analyseren. Misschien is een locatie met veel warehouse repairs traag en kun je meer lokaal oplossen.

→ Days of Broken verkorten = sneller repareren = hogere klanttevredenheid.

onze hoofdvraag: hoe kan je de fietsen beter verdelen zodat er overal genoeg,
readytogo bikes aanwezig te zijn?

eerst willen we alleen kijken voor power 7 en later nog op onderdeel focussen.

om het readytogo bikes beter te verdelen willen we kijken naar: 
inuse, repairs, broken, missing en inventory

- met de inuse/subscriptions willen we kijken hoelang mensen hun fiets hebben en hoevveel er elke maand bijkomen en afgaan.

- met repairs kunnen we kijken hoeveel broken fietsen terug komen om te gebruiken. hier kan ook naar days of broken gekeken worden. en of die in de winkel of warehouse gerepareerd wordt.

- missing bikes die niet terug gevonden worden zullen nieuwe fietsen voor worden neergezet.

- onduidelijk of swaps bij reparaties horen of niet.

- 

- met inventory kunnen we denk ik zien hoeveel er per locatie over blijven en als dat een te hoog aantal is dat we die kunnen verplaatsen.